// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

package entities

// PropostaParecerComite representa a tabela "PropostaParecerComite" do banco de dados.
type PropostaParecerComite struct {
	IDProposta                               string       `json:"idProposta" db:"id_proposta_ppc"`
	Presidente                               bool         `json:"presidente" db:"presidente_ppc"`
	PresidenteData                           *string      `json:"presidenteData" db:"presidente_data_ppc"`
	DiretoriaComp1                           bool         `json:"diretoriaComp1" db:"diretoria_comp1_ppc"`
	DiretoriaComp1Data                       *string      `json:"diretoriaComp1Data" db:"diretoria_comp1_data_ppc"`
	DiretoriaComp2                           bool         `json:"diretoriaComp2" db:"diretoria_comp2_ppc"`
	DiretoriaComp2Data                       *string      `json:"diretoriaComp2Data" db:"diretoria_comp2_data_ppc"`
	Superintendente                          bool         `json:"superintendente" db:"superintendente_ppc"`
	SuperintendenteData                      *string      `json:"superintendenteData" db:"superintendente_data_ppc"`
	InNetworking                             bool         `json:"inNetworking" db:"in_networking_ppc"`
	InNetworkingData                         *string      `json:"inNetworkingData" db:"in_networking_data_ppc"`
}
