// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

package entities

// PropostaParecerComiteHistorico representa a tabela "PropostaParecerComiteHistorico" do banco de dados.
type PropostaParecerComiteHistorico struct {
	IdHistorico                              string       `json:"idHistorico" db:"id_historico_ppch"`
	Presidente                               bool         `json:"presidente" db:"presidente_ppch"`
	PresidenteData                           *string      `json:"presidenteData" db:"presidente_data_ppch"`
	DiretoriaComp1                           bool         `json:"diretoriaComp1" db:"diretoria_comp1_ppch"`
	DiretoriaComp1Data                       *string      `json:"diretoriaComp1Data" db:"diretoria_comp1_data_ppch"`
	DiretoriaComp2                           bool         `json:"diretoriaComp2" db:"diretoria_comp2_ppch"`
	DiretoriaComp2Data                       *string      `json:"diretoriaComp2Data" db:"diretoria_comp2_data_ppch"`
	Superintendente                          bool         `json:"superintendente" db:"superintendente_ppch"`
	SuperintendenteData                      *string      `json:"superintendenteData" db:"superintendente_data_ppch"`
	InNetworking                             bool         `json:"inNetworking" db:"in_networking_ppch"`
	InNetworkingData                         *string      `json:"inNetworkingData" db:"in_networking_data_ppch"`
}
