// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

package entities

// Proposta representa a tabela "Proposta" do banco de dados.
type Proposta struct {
	ID                                       string       `json:"id" db:"id_p"`
	IDUnidade                                string       `json:"idUnidade" db:"id_unidade_p"`
	IDUsuarioCriacao                         string       `json:"idUsuarioCriacao" db:"id_usuario_criacao_p"`
	IDUsuarioUltimaAlt                       *string      `json:"idUsuarioUltimaAlt" db:"id_usuario_ultima_alt_p"`
	IDUsuarioResponsavel                     *string      `json:"idUsuarioResponsavel" db:"id_usuario_responsavel_p"`
	Segmento                                 string       `json:"segmento" db:"segmento_p"`
	TipoOperacao                             string       `json:"tipoOperacao" db:"tipo_operacao_p"`
	ValorProposto                            float64      `json:"valorProposto" db:"valor_proposto_p"`
	Area                                     float64      `json:"area" db:"area_p"`
	Abl                                      *float64     `json:"abl" db:"abl_p"`
	Status                                   string       `json:"status" db:"status_p"`
	DataCriacao                              string       `json:"dataCriacao" db:"data_criacao_p"`
	DataVencimento                           *string      `json:"dataVencimento" db:"data_vencimento_p"`
	NomeFantasia                             *string      `json:"nomeFantasia" db:"nome_fantasia_p"`
	AluguelPercent                           *float64     `json:"aluguelPercent" db:"aluguel_percent_p"`
	PrazoLocacaoMeses                        *int         `json:"prazoLocacaoMeses" db:"prazo_locacao_meses_p"`
	AluguelPorM2                             *float64     `json:"aluguelPorM2" db:"aluguel_por_m2_p"`
	CondominioAprox                          *float64     `json:"condominioAprox" db:"condominio_aprox_p"`
	FppAprox                                 *float64     `json:"fppAprox" db:"fpp_aprox_p"`
	InicioContrato                           *string      `json:"inicioContrato" db:"inicio_contrato_p"`
	FimContrato                              *string      `json:"fimContrato" db:"fim_contrato_p"`
	DataInauguracao                          *string      `json:"dataInauguracao" db:"data_inauguracao_p"`
	Observacoes                              *string      `json:"observacoes" db:"observacoes_p"`
	AtualizadoEm                             string       `json:"atualizadoEm" db:"atualizado_em_p"`
}
