// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

package entities

// PropostaCessaoDireitosHistorico representa a tabela "PropostaCessaoDireitosHistorico" do banco de dados.
type PropostaCessaoDireitosHistorico struct {
	IdHistorico                              string       `json:"idHistorico" db:"id_historico_pcdh"`
	ResSperataProposta                       *float64     `json:"resSperataProposta" db:"res_sperata_proposta_pcdh"`
	ReferenciaMercadoPorM2                   *float64     `json:"referenciaMercadoPorM2" db:"referencia_mercado_por_m2_pcdh"`
	SinalResSperata                          *float64     `json:"sinalResSperata" db:"sinal_res_sperata_pcdh"`
	FormaPagamentoSaldo                      *string      `json:"formaPagamentoSaldo" db:"forma_pagamento_saldo_pcdh"`
	NumParcelas                              *int         `json:"numParcelas" db:"num_parcelas_pcdh"`
	StatusResSperata                         *string      `json:"statusResSperata" db:"status_res_sperata_pcdh"`
	Observacoes                              *string      `json:"observacoes" db:"observacoes_pcdh"`
}
