// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

package entities

// PropostaDocumentoHistorico representa a tabela "PropostaDocumentoHistorico" do banco de dados.
type PropostaDocumentoHistorico struct {
	Id                                       string       `json:"id" db:"id_pdh"`
	IdHistorico                              string       `json:"idHistorico" db:"id_historico_pdh"`
	IdUsuario                                string       `json:"idUsuario" db:"id_usuario_pdh"`
	Codigo                                   string       `json:"codigo" db:"codigo_pdh"`
	NomeOriginal                             string       `json:"nomeOriginal" db:"nome_original_pdh"`
	Tipo                                     string       `json:"tipo" db:"tipo_pdh"`
	Tamanho                                  string       `json:"tamanho" db:"tamanho_pdh"`
	UrlStorage                               *string      `json:"urlStorage" db:"url_storage_pdh"`
	DataUpload                               string       `json:"dataUpload" db:"data_upload_pdh"`
}
