// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

package entities

// PropostaLojaAnterior representa a tabela "PropostaLojaAnterior" do banco de dados.
type PropostaLojaAnterior struct {
	IDProposta                               string       `json:"idProposta" db:"id_proposta_pla"`
	NomeFantasia                             *string      `json:"nomeFantasia" db:"nome_fantasia_pla"`
	Segmento                                 *string      `json:"segmento" db:"segmento_pla"`
	TipoOperacao                             *string      `json:"tipoOperacao" db:"tipo_operacao_pla"`
	Cto                                      *float64     `json:"cto" db:"cto_pla"`
	Abl                                      *float64     `json:"abl" db:"abl_pla"`
	Amm                                      *float64     `json:"amm" db:"amm_pla"`
	DividaAmm                                *float64     `json:"dividaAmm" db:"divida_amm_pla"`
	DividaNegociada                          *float64     `json:"dividaNegociada" db:"divida_negociada_pla"`
	DividaCondominio                         *float64     `json:"dividaCondominio" db:"divida_condominio_pla"`
	DividaFpp                                *float64     `json:"dividaFpp" db:"divida_fpp_pla"`
	FormaPagamento                           *string      `json:"formaPagamento" db:"forma_pagamento_pla"`
}
