// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

package entities

// PropostaTaxaTransferencia representa a tabela "PropostaTaxaTransferencia" do banco de dados.
type PropostaTaxaTransferencia struct {
	IdProposta                               string       `json:"idProposta" db:"id_proposta_ptt"`
	TtContratual                             *float64     `json:"ttContratual" db:"tt_contratual_ptt"`
	TtProposta                               *float64     `json:"ttProposta" db:"tt_proposta_ptt"`
	TtPropostaNumAmm                         *float64     `json:"ttPropostaNumAmm" db:"tt_proposta_num_amm_ptt"`
	SinalTt                                  *float64     `json:"sinalTt" db:"sinal_tt_ptt"`
	FormaPagamentoTt                         *string      `json:"formaPagamentoTt" db:"forma_pagamento_tt_ptt"`
	JustificativaTt                          *string      `json:"justificativaTt" db:"justificativa_tt_ptt"`
	StatusTt                                 *string      `json:"statusTt" db:"status_tt_ptt"`
}
