// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

package entities

// PropostaNecessidadesTecnicasHistorico representa a tabela "PropostaNecessidadesTecnicasHistorico" do banco de dados.
type PropostaNecessidadesTecnicasHistorico struct {
	IdHistorico                              string       `json:"idHistorico" db:"id_historico_pnth"`
	DemandaEletricaKva                       *float64     `json:"demandaEletricaKva" db:"demanda_eletrica_kva_pnth"`
	TensaoNecessaria                         *string      `json:"tensaoNecessaria" db:"tensao_necessaria_pnth"`
	CircuitosEspeciais                       bool         `json:"circuitosEspeciais" db:"circuitos_especiais_pnth"`
	ObsEletrica                              *string      `json:"obsEletrica" db:"obs_eletrica_pnth"`
	PontoAgua                                bool         `json:"pontoAgua" db:"ponto_agua_pnth"`
	QuantidadePontosAgua                     *int         `json:"quantidadePontosAgua" db:"quantidade_pontos_agua_pnth"`
	PontoEsgoto                              bool         `json:"pontoEsgoto" db:"ponto_esgoto_pnth"`
	VazaoNecessariaLmin                      *float64     `json:"vazaoNecessariaLmin" db:"vazao_necessaria_lmin_pnth"`
	CaixaGordura                             bool         `json:"caixaGordura" db:"caixa_gordura_pnth"`
	ObsHidraulica                            *string      `json:"obsHidraulica" db:"obs_hidraulica_pnth"`
	NecessitaGas                             bool         `json:"necessitaGas" db:"necessita_gas_pnth"`
	TipoGas                                  *string      `json:"tipoGas" db:"tipo_gas_pnth"`
	ConsumoGasM3h                            *float64     `json:"consumoGasM3h" db:"consumo_gas_m3h_pnth"`
	ObsGas                                   *string      `json:"obsGas" db:"obs_gas_pnth"`
	NecessitaExaustao                        bool         `json:"necessitaExaustao" db:"necessita_exaustao_pnth"`
	VazaoExaustaoM3h                         *float64     `json:"vazaoExaustaoM3h" db:"vazao_exaustao_m3h_pnth"`
	NecessitaMakeUpAr                        bool         `json:"necessitaMakeUpAr" db:"necessita_make_up_ar_pnth"`
	ObsVentilacao                            *string      `json:"obsVentilacao" db:"obs_ventilacao_pnth"`
	AreaMinimaM2                             *float64     `json:"areaMinimaM2" db:"area_minima_m2_pnth"`
	AreaMaximaM2                             *float64     `json:"areaMaximaM2" db:"area_maxima_m2_pnth"`
	PeDireitoMinimoM                         *float64     `json:"peDireitoMinimoM" db:"pe_direito_minimo_m_pnth"`
	CargaPisoKgm2                            *float64     `json:"cargaPisoKgm2" db:"carga_piso_kgm2_pnth"`
	NecessitaMezanino                        bool         `json:"necessitaMezanino" db:"necessita_mezanino_pnth"`
	ObsEstrutura                             *string      `json:"obsEstrutura" db:"obs_estrutura_pnth"`
	FrenteMinimaM                            *float64     `json:"frenteMinimaM" db:"frente_minima_m_pnth"`
	TipoFachada                              *string      `json:"tipoFachada" db:"tipo_fachada_pnth"`
	ComunicacaoVisualLed                     bool         `json:"comunicacaoVisualLed" db:"comunicacao_visual_led_pnth"`
	ObsFachada                               *string      `json:"obsFachada" db:"obs_fachada_pnth"`
	PontosDados                              *int         `json:"pontosDados" db:"pontos_dados_pnth"`
	NecessitaFibra                           bool         `json:"necessitaFibra" db:"necessita_fibra_pnth"`
	ObsTelecom                               *string      `json:"obsTelecom" db:"obs_telecom_pnth"`
	Status                                   *string      `json:"status" db:"status_pnth"`
	IdUsuarioResponsavel                     *string      `json:"idUsuarioResponsavel" db:"id_usuario_responsavel_pnth"`
	CriadoEm                                 *string      `json:"criadoEm" db:"criado_em_pnth"`
	AtualizadoEm                             *string      `json:"atualizadoEm" db:"atualizado_em_pnth"`
}
