// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

package entities

// PropostaCessaoDireitos representa a tabela "PropostaCessaoDireitos" do banco de dados.
type PropostaCessaoDireitos struct {
	IdProposta                               string       `json:"idProposta" db:"id_proposta_pcd"`
	ResSperataProposta                       *float64     `json:"resSperataProposta" db:"res_sperata_proposta_pcd"`
	ReferenciaMercadoPorM2                   *float64     `json:"referenciaMercadoPorM2" db:"referencia_mercado_por_m2_pcd"`
	SinalResSperata                          *float64     `json:"sinalResSperata" db:"sinal_res_sperata_pcd"`
	FormaPagamentoSaldo                      *string      `json:"formaPagamentoSaldo" db:"forma_pagamento_saldo_pcd"`
	NumParcelas                              *int         `json:"numParcelas" db:"num_parcelas_pcd"`
	StatusResSperata                         *string      `json:"statusResSperata" db:"status_res_sperata_pcd"`
	Observacoes                              *string      `json:"observacoes" db:"observacoes_pcd"`
}
