// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

package entities

// PropostaDocumento representa a tabela "PropostaDocumento" do banco de dados.
type PropostaDocumento struct {
	ID                                       string       `json:"id" db:"id_pd"`
	IDProposta                               string       `json:"idProposta" db:"id_proposta_pd"`
	IDUsuario                                string       `json:"idUsuario" db:"id_usuario_pd"`
	Codigo                                   string       `json:"codigo" db:"codigo_pd"`
	NomeOriginal                             string       `json:"nomeOriginal" db:"nome_original_pd"`
	Tipo                                     string       `json:"tipo" db:"tipo_pd"`
	Tamanho                                  string       `json:"tamanho" db:"tamanho_pd"`
	URLStorage                               *string      `json:"urlStorage" db:"url_storage_pd"`
	DataUpload                               string       `json:"dataUpload" db:"data_upload_pd"`
}
