// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

/** Representa a tabela "Proposta" do banco de dados. */
export interface Proposta {
  id: string;
  idUnidade: string;
  idUsuarioCriacao: string;
  idUsuarioUltimaAlt?: string | null;
  idUsuarioResponsavel?: string | null;
  segmento: string;
  tipoOperacao: string;
  valorProposto: number;
  area: number;
  abl?: number | null;
  status: string;
  dataCriacao: string;
  dataVencimento?: string | null;
  nomeFantasia?: string | null;
  aluguelPercent?: number | null;
  prazoLocacaoMeses?: number | null;
  aluguelPorM2?: number | null;
  condominioAprox?: number | null;
  fppAprox?: number | null;
  inicioContrato?: string | null;
  fimContrato?: string | null;
  dataInauguracao?: string | null;
  observacoes?: string | null;
  atualizadoEm: string;
}
