// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

package entities

// PropostaHistorico representa a tabela "PropostaHistorico" do banco de dados.
type PropostaHistorico struct {
	ID                                       string       `json:"id" db:"id_ph"`
	IDProposta                               string       `json:"idProposta" db:"id_proposta_ph"`
	IDUsuario                                string       `json:"idUsuario" db:"id_usuario_ph"`
	EditadoEm                                string       `json:"editadoEm" db:"editado_em_ph"`
}
