// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

package entities

// PropostaLojaAnteriorHistorico representa a tabela "PropostaLojaAnteriorHistorico" do banco de dados.
type PropostaLojaAnteriorHistorico struct {
	IDHistorico                              string       `json:"idHistorico" db:"id_historico_plah"`
	NomeFantasia                             *string      `json:"nomeFantasia" db:"nome_fantasia_plah"`
	Segmento                                 *string      `json:"segmento" db:"segmento_plah"`
	TipoOperacao                             *string      `json:"tipoOperacao" db:"tipo_operacao_plah"`
	Cto                                      *float64     `json:"cto" db:"cto_plah"`
	Abl                                      *float64     `json:"abl" db:"abl_plah"`
	Amm                                      *float64     `json:"amm" db:"amm_plah"`
	DividaAmm                                *float64     `json:"dividaAmm" db:"divida_amm_plah"`
	DividaNegociada                          *float64     `json:"dividaNegociada" db:"divida_negociada_plah"`
	DividaCondominio                         *float64     `json:"dividaCondominio" db:"divida_condominio_plah"`
	DividaFpp                                *float64     `json:"dividaFpp" db:"divida_fpp_plah"`
	FormaPagamento                           *string      `json:"formaPagamento" db:"forma_pagamento_plah"`
}
