// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

/** Representa a tabela "PropostaLojaAnteriorHistorico" do banco de dados. */
export interface PropostaLojaAnteriorHistorico {
  idHistorico: string;
  nomeFantasia?: string | null;
  segmento?: string | null;
  tipoOperacao?: string | null;
  cto?: number | null;
  abl?: number | null;
  amm?: number | null;
  dividaAmm?: number | null;
  dividaNegociada?: number | null;
  dividaCondominio?: number | null;
  dividaFpp?: number | null;
  formaPagamento?: string | null;
}
