// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

/** Representa a tabela "PropostaNecessidadesTecnicas" do banco de dados. */
export interface PropostaNecessidadesTecnicas {
  idProposta: string;
  demandaEletricaKva?: number | null;
  tensaoNecessaria?: string | null;
  circuitosEspeciais?: boolean;
  obsEletrica?: string | null;
  pontoAgua?: boolean;
  quantidadePontosAgua?: number | null;
  pontoEsgoto?: boolean;
  vazaoNecessariaLmin?: number | null;
  caixaGordura?: boolean;
  obsHidraulica?: string | null;
  necessitaGas?: boolean;
  tipoGas?: string | null;
  consumoGasM3h?: number | null;
  obsGas?: string | null;
  necessitaExaustao?: boolean;
  vazaoExaustaoM3h?: number | null;
  necessitaMakeUpAr?: boolean;
  obsVentilacao?: string | null;
  areaMinimaM2?: number | null;
  areaMaximaM2?: number | null;
  peDireitoMinimoM?: number | null;
  cargaPisoKgm2?: number | null;
  necessitaMezanino?: boolean;
  obsEstrutura?: string | null;
  frenteMinimaM?: number | null;
  tipoFachada?: string | null;
  comunicacaoVisualLed?: boolean;
  obsFachada?: string | null;
  pontosDados?: number | null;
  necessitaFibra?: boolean;
  obsTelecom?: string | null;
  status?: string | null;
  idUsuarioResponsavel?: string | null;
  criadoEm: string;
  atualizadoEm?: string | null;
}
