// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

package entities

// PropostaTaxaTransferenciaHistorico representa a tabela "PropostaTaxaTransferenciaHistorico" do banco de dados.
type PropostaTaxaTransferenciaHistorico struct {
	IDHistorico                              string       `json:"idHistorico" db:"id_historico_ptth"`
	TtContratual                             *float64     `json:"ttContratual" db:"tt_contratual_ptth"`
	TtProposta                               *float64     `json:"ttProposta" db:"tt_proposta_ptth"`
	TtPropostaNumAmm                         *float64     `json:"ttPropostaNumAmm" db:"tt_proposta_num_amm_ptth"`
	SinalTt                                  *float64     `json:"sinalTt" db:"sinal_tt_ptth"`
	FormaPagamentoTt                         *string      `json:"formaPagamentoTt" db:"forma_pagamento_tt_ptth"`
	JustificativaTt                          *string      `json:"justificativaTt" db:"justificativa_tt_ptth"`
	StatusTt                                 *string      `json:"statusTt" db:"status_tt_ptth"`
}
