// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

/** Representa a tabela "PropostaParecerComiteHistorico" do banco de dados. */
export interface PropostaParecerComiteHistorico {
  idHistorico: string;
  presidente: boolean;
  presidenteData?: string | null;
  diretoriaComp1: boolean;
  diretoriaComp1Data?: string | null;
  diretoriaComp2: boolean;
  diretoriaComp2Data?: string | null;
  superintendente: boolean;
  superintendenteData?: string | null;
  inNetworking: boolean;
  inNetworkingData?: string | null;
}
