// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

package entities

// PropostaNecessidadesTecnicas representa a tabela "PropostaNecessidadesTecnicas" do banco de dados.
type PropostaNecessidadesTecnicas struct {
	IDProposta                               string       `json:"idProposta" db:"id_proposta_pnt"`
	DemandaEletricaKva                       *float64     `json:"demandaEletricaKva" db:"demanda_eletrica_kva_pnt"`
	TensaoNecessaria                         *string      `json:"tensaoNecessaria" db:"tensao_necessaria_pnt"`
	CircuitosEspeciais                       bool         `json:"circuitosEspeciais" db:"circuitos_especiais_pnt"`
	ObsEletrica                              *string      `json:"obsEletrica" db:"obs_eletrica_pnt"`
	PontoAgua                                bool         `json:"pontoAgua" db:"ponto_agua_pnt"`
	QuantidadePontosAgua                     *int         `json:"quantidadePontosAgua" db:"quantidade_pontos_agua_pnt"`
	PontoEsgoto                              bool         `json:"pontoEsgoto" db:"ponto_esgoto_pnt"`
	VazaoNecessariaLmin                      *float64     `json:"vazaoNecessariaLmin" db:"vazao_necessaria_lmin_pnt"`
	CaixaGordura                             bool         `json:"caixaGordura" db:"caixa_gordura_pnt"`
	ObsHidraulica                            *string      `json:"obsHidraulica" db:"obs_hidraulica_pnt"`
	NecessitaGas                             bool         `json:"necessitaGas" db:"necessita_gas_pnt"`
	TipoGas                                  *string      `json:"tipoGas" db:"tipo_gas_pnt"`
	ConsumoGasM3h                            *float64     `json:"consumoGasM3h" db:"consumo_gas_m3h_pnt"`
	ObsGas                                   *string      `json:"obsGas" db:"obs_gas_pnt"`
	NecessitaExaustao                        bool         `json:"necessitaExaustao" db:"necessita_exaustao_pnt"`
	VazaoExaustaoM3h                         *float64     `json:"vazaoExaustaoM3h" db:"vazao_exaustao_m3h_pnt"`
	NecessitaMakeUpAr                        bool         `json:"necessitaMakeUpAr" db:"necessita_make_up_ar_pnt"`
	ObsVentilacao                            *string      `json:"obsVentilacao" db:"obs_ventilacao_pnt"`
	AreaMinimaM2                             *float64     `json:"areaMinimaM2" db:"area_minima_m2_pnt"`
	AreaMaximaM2                             *float64     `json:"areaMaximaM2" db:"area_maxima_m2_pnt"`
	PeDireitoMinimoM                         *float64     `json:"peDireitoMinimoM" db:"pe_direito_minimo_m_pnt"`
	CargaPisoKgm2                            *float64     `json:"cargaPisoKgm2" db:"carga_piso_kgm2_pnt"`
	NecessitaMezanino                        bool         `json:"necessitaMezanino" db:"necessita_mezanino_pnt"`
	ObsEstrutura                             *string      `json:"obsEstrutura" db:"obs_estrutura_pnt"`
	FrenteMinimaM                            *float64     `json:"frenteMinimaM" db:"frente_minima_m_pnt"`
	TipoFachada                              *string      `json:"tipoFachada" db:"tipo_fachada_pnt"`
	ComunicacaoVisualLed                     bool         `json:"comunicacaoVisualLed" db:"comunicacao_visual_led_pnt"`
	ObsFachada                               *string      `json:"obsFachada" db:"obs_fachada_pnt"`
	PontosDados                              *int         `json:"pontosDados" db:"pontos_dados_pnt"`
	NecessitaFibra                           bool         `json:"necessitaFibra" db:"necessita_fibra_pnt"`
	ObsTelecom                               *string      `json:"obsTelecom" db:"obs_telecom_pnt"`
	Status                                   *string      `json:"status" db:"status_pnt"`
	IDUsuarioResponsavel                     *string      `json:"idUsuarioResponsavel" db:"id_usuario_responsavel_pnt"`
	CriadoEm                                 string       `json:"criadoEm" db:"criado_em_pnt"`
	AtualizadoEm                             *string      `json:"atualizadoEm" db:"atualizado_em_pnt"`
}
