// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

/** Representa a tabela "PropostaDocumento" do banco de dados. */
export interface PropostaDocumento {
  id: string;
  idProposta: string;
  idUsuario: string;
  codigo: string;
  nomeOriginal: string;
  tipo: string;
  tamanho: string;
  urlStorage?: string | null;
  dataUpload: string;
}
