// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

/** Representa a tabela "PropostaCessaoDireitosHistorico" do banco de dados. */
export interface PropostaCessaoDireitosHistorico {
  idHistorico: string;
  resSperataProposta?: number | null;
  referenciaMercadoPorM2?: number | null;
  sinalResSperata?: number | null;
  formaPagamentoSaldo?: string | null;
  numParcelas?: number | null;
  statusResSperata?: string | null;
  observacoes?: string | null;
}
