// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

package entities

// PropostaHistorico representa a tabela "PropostaHistorico" do banco de dados.
type PropostaHistorico struct {
	Id                                       string       `json:"id" db:"id_ph"`
	IdProposta                               string       `json:"idProposta" db:"id_proposta_ph"`
	IdUsuario                                string       `json:"idUsuario" db:"id_usuario_ph"`
	EditadoEm                                string       `json:"editadoEm" db:"editado_em_ph"`
	CodigoUnidade                            *string      `json:"codigoUnidade" db:"codigo_unidade_ph"`
	Segmento                                 *string      `json:"segmento" db:"segmento_ph"`
	TipoOperacao                             *string      `json:"tipoOperacao" db:"tipo_operacao_ph"`
	ValorProposto                            *float64     `json:"valorProposto" db:"valor_proposto_ph"`
	Area                                     *float64     `json:"area" db:"area_ph"`
	Abl                                      *float64     `json:"abl" db:"abl_ph"`
	Status                                   *string      `json:"status" db:"status_ph"`
	DataCriacao                              *string      `json:"dataCriacao" db:"data_criacao_ph"`
	DataVencimento                           *string      `json:"dataVencimento" db:"data_vencimento_ph"`
	NomeFantasia                             *string      `json:"nomeFantasia" db:"nome_fantasia_ph"`
	AluguelPercent                           *float64     `json:"aluguelPercent" db:"aluguel_percent_ph"`
	PrazoLocacaoMeses                        *int         `json:"prazoLocacaoMeses" db:"prazo_locacao_meses_ph"`
	AluguelPorM2                             *float64     `json:"aluguelPorM2" db:"aluguel_por_m2_ph"`
	CondominioAprox                          *float64     `json:"condominioAprox" db:"condominio_aprox_ph"`
	FppAprox                                 *float64     `json:"fppAprox" db:"fpp_aprox_ph"`
	InicioContrato                           *string      `json:"inicioContrato" db:"inicio_contrato_ph"`
	FimContrato                              *string      `json:"fimContrato" db:"fim_contrato_ph"`
	DataInauguracao                          *string      `json:"dataInauguracao" db:"data_inauguracao_ph"`
	Observacoes                              *string      `json:"observacoes" db:"observacoes_ph"`
	AtualizadoEmSnapshot                     *string      `json:"atualizadoEmSnapshot" db:"atualizado_em_snapshot_ph"`
}
