// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

/** Representa a tabela "Unidade" do banco de dados. */
export interface Unidade {
  id: string;
  codigo: string;
  piso: string;
  corredor: string;
  area: number;
  criadoEm: string;
}
