// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

package entities

// Unidade representa a tabela "Unidade" do banco de dados.
type Unidade struct {
	ID                                       string       `json:"id" db:"id_un"`
	Codigo                                   string       `json:"codigo" db:"codigo_un"`
	Piso                                     string       `json:"piso" db:"piso_un"`
	Corredor                                 string       `json:"corredor" db:"corredor_un"`
	Area                                     float64      `json:"area" db:"area_un"`
	CriadoEm                                 string       `json:"criadoEm" db:"criado_em_un"`
}
