// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

package entities

// Usuario representa a tabela "Usuario" do banco de dados.
type Usuario struct {
	Id                                       string       `json:"id" db:"id_u"`
	Nome                                     string       `json:"nome" db:"nome_u"`
	Email                                    string       `json:"email" db:"email_u"`
	SenhaHash                                string       `json:"senhaHash" db:"senha_hash_u"`
	Setor                                    *string      `json:"setor" db:"setor_u"`
	CriadoEm                                 string       `json:"criadoEm" db:"criado_em_u"`
}
