// ============================================================
// entities/index.ts — Re-exporta todas as interfaces de entidade
// ============================================================
//
// Ponto de entrada único para importar tipos de entidades do banco.
// Gerado automaticamente pelo codegen (codegen/generate.go).
//
// Uso:
//   import type { Proposta, Unidade } from '../entities';
//
// NUNCA edite este arquivo manualmente. Para atualizar após uma
// migration SQL, execute na raiz do projeto:
//   .\ajustar entidades via migration.ps1
// ============================================================
// Code generated by codegen/generate.go — DO NOT EDIT.
// Importa todas as entidades em um único ponto.

export * from './proposta';
export * from './proposta_cessao_direitos';
export * from './proposta_cessao_direitos_historico';
export * from './proposta_documento';
export * from './proposta_documento_historico';
export * from './proposta_historico';
export * from './proposta_loja_anterior';
export * from './proposta_loja_anterior_historico';
export * from './proposta_necessidades_tecnicas';
export * from './proposta_necessidades_tecnicas_historico';
export * from './proposta_parecer_comite';
export * from './proposta_parecer_comite_historico';
export * from './proposta_taxa_transferencia';
export * from './proposta_taxa_transferencia_historico';
export * from './unidade';
export * from './usuario';
