// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

export * from './usuario';
export * from './unidade';
export * from './proposta';
export * from './proposta_loja_anterior';
export * from './proposta_necessidades_tecnicas';
export * from './proposta_cessao_direitos';
export * from './proposta_taxa_transferencia';
export * from './proposta_parecer_comite';
export * from './proposta_documento';
export * from './proposta_historico';
export * from './proposta_loja_anterior_historico';
export * from './proposta_necessidades_tecnicas_historico';
export * from './proposta_cessao_direitos_historico';
export * from './proposta_taxa_transferencia_historico';
export * from './proposta_parecer_comite_historico';
