// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: .\codegen\generate.ps1

/** Representa a tabela "PropostaTaxaTransferencia" do banco de dados. */
export interface PropostaTaxaTransferencia {
  idProposta: string;
  ttContratual?: number | null;
  ttProposta?: number | null;
  ttPropostaNumAmm?: number | null;
  sinalTt?: number | null;
  formaPagamentoTt?: string | null;
  justificativaTt?: string | null;
  statusTt?: string | null;
}
