// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

/** Representa a tabela "PropostaHistorico" do banco de dados.
 *  Espelha os campos da tabela Proposta no momento da edição.
 *  Sem FK para Unidade — codigo armazenado como texto. */
export interface PropostaHistorico {
  id: string;
  idProposta: string;
  idUsuario: string;
  editadoEm: string;

  codigoUnidade?: string | null;
  segmento?: string | null;
  tipoOperacao?: string | null;
  valorProposto?: number | null;
  area?: number | null;
  abl?: number | null;
  status?: string | null;
  dataCriacao?: string | null;
  dataVencimento?: string | null;
  nomeFantasia?: string | null;
  aluguelPercent?: number | null;
  prazoLocacaoMeses?: number | null;
  aluguelPorM2?: number | null;
  condominioAprox?: number | null;
  fppAprox?: number | null;
  inicioContrato?: string | null;
  fimContrato?: string | null;
  dataInauguracao?: string | null;
  observacoes?: string | null;
  atualizadoEmSnapshot?: string | null;
}
