// Code generated by codegen/generate.go — DO NOT EDIT.
// Atualize rodando: go run ./codegen/generate.go

/** Representa a tabela "Usuario" do banco de dados. */
export interface Usuario {
  id: string;
  nome: string;
  email: string;
  senhaHash: string;
  setor?: string | null;
  criadoEm: string;
}
