//go:generate go run generate.go
// ============================================================
// codegen/generate.go — Gerador automático de entidades
// ============================================================
//
// Lê todas as migrations *.up.sql em ordem alfabética e gera:
//
//   entities/*.go             → structs Go com tags json e db
//   entities/*.ts             → interfaces TypeScript
//   API/internal/entities/*.go → cópia para o backend
//   Figma/src/app/entities/*.ts → cópia para o frontend
//
// Como usar (raiz do projeto):
//   .\ajustar entidades via migration.ps1
//   ou: go run ./codegen/generate.go [caminho-raiz]
//
// Convenções de nomenclatura:
//   Coluna: nome_fantasia_p  →  Go: NomeFantasia  TS: nomeFantasia
//   O sufixo de tabela (_p, _un, _pla, etc.) é removido automaticamente.
//   Campos nullable → Go: *string, *float64 etc. | TS: string | null
//
// Para adicionar uma nova entidade:
//   1. Criar migration SQL em API/migrations/NNNNN_nome.up.sql
//   2. Executar .\ajustar entidades via migration.ps1
//   3. Os arquivos serão gerados/atualizados automaticamente
// ============================================================
// Lê todas as migrations *.up.sql e gera:
//   - entities/*.go + entities/*.ts        (pasta raiz do projeto)
//   - API/internal/entities/*.go           (para o backend Go)
//   - Figma/src/app/entities/*.ts          (para o frontend React)
//
// Uso:
//   go run ./codegen/generate.go [raiz-do-projeto]
//   ou via PowerShell:
//   .\codegen\generate.ps1
// ============================================================
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

var sqlToGo = map[string]string{
	"UUID": "string", "VARCHAR": "string", "CHAR": "string", "TEXT": "string",
	"DECIMAL": "float64", "NUMERIC": "float64",
	"INTEGER": "int", "INT": "int", "BIGINT": "int64", "SMALLINT": "int16",
	"BOOLEAN": "bool",
	"TIMESTAMP": "string", "TIMESTAMPTZ": "string", "DATE": "string",
}

var sqlToTS = map[string]string{
	"UUID": "string", "VARCHAR": "string", "CHAR": "string", "TEXT": "string",
	"DECIMAL": "number", "NUMERIC": "number",
	"INTEGER": "number", "INT": "number", "BIGINT": "number", "SMALLINT": "number",
	"BOOLEAN": "boolean",
	"TIMESTAMP": "string", "TIMESTAMPTZ": "string", "DATE": "string",
}

type Column struct {
	DBName   string
	SQLType  string
	Nullable bool
	IsPK     bool
}

type Table struct {
	Name    string
	Columns []Column
}

func colToCamel(col string) string {
	parts := strings.Split(col, "_")
	suffix := parts[len(parts)-1]
	if len(suffix) <= 4 && isAlpha(suffix) {
		parts = parts[:len(parts)-1]
	}
	if len(parts) == 0 {
		return col
	}
	result := parts[0]
	for _, p := range parts[1:] {
		result += strings.Title(p)
	}
	return result
}

func isAlpha(s string) bool {
	for _, r := range s {
		if !unicode.IsLetter(r) {
			return false
		}
	}
	return true
}

func camelToPascal(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func tableToFileName(name string) string {
	re := regexp.MustCompile(`([A-Z])`)
	snake := re.ReplaceAllStringFunc(name, func(s string) string {
		return "_" + strings.ToLower(s)
	})
	return strings.TrimPrefix(snake, "_")
}

var tableRe = regexp.MustCompile(`(?s)CREATE TABLE "(\w+)" \((.*?)\);`)
var colRe   = regexp.MustCompile(`^(\w+)\s+(\w+(?:\(\d+(?:,\d+)?\))?)(.*)$`)

func parseSQL(sql string) []Table {
	matches := tableRe.FindAllStringSubmatch(sql, -1)
	var tables []Table
	for _, m := range matches {
		tableName := m[1]
		body := m[2]
		var cols []Column
		for _, line := range strings.Split(body, "\n") {
			line = strings.TrimSpace(strings.TrimRight(line, ","))
			if line == "" || strings.HasPrefix(line, "--") {
				continue
			}
			up := strings.ToUpper(line)
			skip := []string{"CONSTRAINT", "CREATE", "PRIMARY KEY (", "UNIQUE (", "CHECK ("}
			skipped := false
			for _, s := range skip {
				if strings.HasPrefix(up, s) { skipped = true; break }
			}
			if skipped { continue }
			cm := colRe.FindStringSubmatch(line)
			if cm == nil { continue }
			colName := cm[1]
			sqlType := strings.ToUpper(strings.Split(cm[2], "(")[0])
			rest := strings.ToUpper(cm[3])
			isPK := strings.Contains(rest, "PRIMARY KEY")
			notNull := strings.Contains(rest, "NOT NULL") || isPK
			cols = append(cols, Column{
				DBName: colName, SQLType: sqlType,
				Nullable: !notNull, IsPK: isPK,
			})
		}
		tables = append(tables, Table{Name: tableName, Columns: cols})
	}
	return tables
}

func generateGo(t Table) string {
	var sb strings.Builder
	sb.WriteString("// Code generated by codegen/generate.go — DO NOT EDIT.\n")
	sb.WriteString("// Atualize rodando: .\\codegen\\generate.ps1\n\n")
	sb.WriteString("package entities\n\n")
	sb.WriteString(fmt.Sprintf("// %s representa a tabela \"%s\" do banco de dados.\n", t.Name, t.Name))
	sb.WriteString(fmt.Sprintf("type %s struct {\n", t.Name))
	for _, col := range t.Columns {
		camel := colToCamel(col.DBName)
		pascal := camelToPascal(camel)
		goT := sqlToGo[col.SQLType]
		if goT == "" { goT = "string" }
		if col.Nullable && !col.IsPK && col.SQLType != "BOOLEAN" {
			goT = "*" + goT
		}
		sb.WriteString(fmt.Sprintf("\t%-40s %-12s `json:\"%s\" db:\"%s\"`\n",
			pascal, goT, camel, col.DBName))
	}
	sb.WriteString("}\n")
	return sb.String()
}

func generateTS(t Table) string {
	var sb strings.Builder
	sb.WriteString("// Code generated by codegen/generate.go — DO NOT EDIT.\n")
	sb.WriteString("// Atualize rodando: .\\codegen\\generate.ps1\n\n")
	sb.WriteString(fmt.Sprintf("/** Representa a tabela \"%s\" do banco de dados. */\n", t.Name))
	sb.WriteString(fmt.Sprintf("export interface %s {\n", t.Name))
	for _, col := range t.Columns {
		camel := colToCamel(col.DBName)
		tsT := sqlToTS[col.SQLType]
		if tsT == "" { tsT = "string" }
		opt := ""
		if col.Nullable && col.SQLType != "BOOLEAN" {
			tsT += " | null"; opt = "?"
		}
		sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", camel, opt, tsT))
	}
	sb.WriteString("}\n")
	return sb.String()
}

func writeFile(path, content string) {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Erro criando dir %s: %v\n", filepath.Dir(path), err)
		return
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Erro escrevendo %s: %v\n", path, err)
		return
	}
	fmt.Printf("  ✓ %s\n", path)
}

func main() {
	// Raiz do projeto: argumento ou diretório pai do codegen
	root := ""
	if len(os.Args) > 1 {
		root = os.Args[1]
	} else {
		// Tentar achar subindo de onde o binário está
		dir, _ := os.Getwd()
		for i := 0; i < 5; i++ {
			if _, err := os.Stat(filepath.Join(dir, "API")); err == nil {
				root = dir; break
			}
			dir = filepath.Dir(dir)
		}
	}
	if root == "" {
		fmt.Fprintln(os.Stderr, "Erro: raiz do projeto não encontrada. Passe o caminho como argumento.")
		os.Exit(1)
	}

	migrationsDir := filepath.Join(root, "API", "migrations")
	files, _ := filepath.Glob(filepath.Join(migrationsDir, "*.up.sql"))
	sort.Strings(files)

	if len(files) == 0 {
		fmt.Fprintf(os.Stderr, "Nenhuma migration encontrada em %s\n", migrationsDir)
		os.Exit(1)
	}

	var fullSQL strings.Builder
	for _, f := range files {
		data, _ := os.ReadFile(f)
		fullSQL.Write(data)
		fullSQL.WriteString("\n")
	}

	tables := parseSQL(fullSQL.String())
	fmt.Printf("Encontradas %d tabelas em %s\n\n", len(tables), migrationsDir)

	// Pastas de saída
	entitiesDir    := filepath.Join(root, "entities")
	goEntitiesDir  := filepath.Join(root, "API", "internal", "entities")
	tsEntitiesDir  := filepath.Join(root, "Figma", "src", "app", "entities")

	// index.ts
	var indexLines []string
	indexLines = append(indexLines, "// Code generated by codegen/generate.go — DO NOT EDIT.")
	indexLines = append(indexLines, "// Atualize rodando: .\\codegen\\generate.ps1")
	indexLines = append(indexLines, "")

	for _, t := range tables {
		fileName := tableToFileName(t.Name)
		goContent := generateGo(t)
		tsContent := generateTS(t)

		writeFile(filepath.Join(entitiesDir, fileName+".go"), goContent)
		writeFile(filepath.Join(entitiesDir, fileName+".ts"), tsContent)
		writeFile(filepath.Join(goEntitiesDir, fileName+".go"), goContent)
		writeFile(filepath.Join(tsEntitiesDir, fileName+".ts"), tsContent)

		indexLines = append(indexLines, fmt.Sprintf("export * from './%s';", fileName))
	}

	indexLines = append(indexLines, "")
	writeFile(filepath.Join(tsEntitiesDir, "index.ts"), strings.Join(indexLines, "\n"))
	writeFile(filepath.Join(entitiesDir, "index.ts"), strings.Join(indexLines, "\n"))

	fmt.Printf("\nPronto! %d entidades geradas.\n", len(tables))
}
